
name: Node.js CI

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: macos-latest

    strategy:
      matrix:
        node-version:
          - 14.x

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: yarn --frozen-lockfile
    - run: yarn lint
    - run: yarn electron:build
      env:
        CI: true
    - name: upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: seana
        path: dist_electron/Seana-*.dmg
        if-no-files-found: error
